[Java][SDK 953] Log listener callback added
Countly/countly-sdk-documentation pull request #282
Opened 2023-01-11 11:05 UTC by ZahidZafar

2023-01-11 14:01 UTC, turtledreams approved these changes

2023-01-13 11:31 UTC, ArtursKadikis requested changes
Please change this to an inline listener

2023-01-16 09:34 UTC, ArtursKadikis requested changes
needs to be reworked

2023-01-17 10:52 UTC, ArtursKadikis approved these changes

2023-01-17 10:52 UTC, merged