config object documentation
Countly/countly-sdk-documentation pull request #330
Opened 2023-03-29 11:49 UTC by peterbrown0

2023-03-31 12:01 UTC, ArtursKadikis requested changes
let's try creating all configuration examples as per this:

const countlyConfig = new CountlyConfig(SERVER_URL, APP_KEY);

//set the ... (describing the feature specific thing) 
countlyConfig.setDeviceId("TemporaryDeviceID");

await Countly.initWithConfig(countlyConfig);

2023-04-03 10:14 UTC, peterbrown0 commented on react_native_bridged/next.md
> +<h2>Init (Deprecated)</h2>
Done

2023-04-03 10:46 UTC, ArtursKadikis requested changes
Rework consent section, rework "init configuration" examples

2023-04-04 11:17 UTC, turtledreams approved these changes
looks cool. grammatically decent. just capitalized titles. header levels are correct. nothing that can staph a merge strike me eye

2023-04-04 11:28 UTC, ArtursKadikis requested changes
add documentation for the new attribution calls

2023-04-25 13:49 UTC, merged