updating the docs
Countly/countly-sdk-documentation pull request #364
Opened 2023-07-10 11:10 UTC by peterbrown0

2023-07-10 11:21 UTC, turtledreams commented on react_native_bridged/next.md
> +  devices), set the push token mode. This allows you to choose either, test or
if not targeting iOS we should not set the push token mode?

2023-07-10 11:24 UTC, turtledreams commented on react_native_bridged/next.md
> +// Set push token type NB: ONLY FOR iOS
is this nota bene?

2023-07-10 11:28 UTC, turtledreams commented on react_native_bridged/next.md
> +<pre>// create Countly config object
there seems to be code only usable when targeting ios or android. if that is the case it might be beneficial to use tabs like this:
![image](https://github.com/Countly/countly-sdk-documentation/assets/62231246/12bb9fef-135f-4ff9-b6fa-33e3a4e0e14e)
what do you say?

2023-07-10 13:23 UTC, peterbrown0 commented on react_native_bridged/next.md
> +  devices), set the push token mode. This allows you to choose either, test or
yes. @ArtursKadikis can you please confirm this?

2023-07-10 13:28 UTC, peterbrown0 commented on react_native_bridged/next.md
> +// Set push token type NB: ONLY FOR iOS
yes

2023-07-10 13:28 UTC, peterbrown0 commented on react_native_bridged/next.md
> +<pre>// create Countly config object
agreed

2023-07-10 13:31 UTC, turtledreams commented on react_native_bridged/next.md
> +  devices), set the push token mode. This allows you to choose either, test or
then you should mention it clearly

2023-07-10 13:33 UTC, turtledreams commented on react_native_bridged/next.md
> +// Set push token type NB: ONLY FOR iOS
its not common lingo peter. I am ecstatic to see your inclination to literacy but please change that. or remove that when you create tabs

2023-07-10 20:04 UTC, peterbrown0 commented on react_native_bridged/next.md
> +// Set push token type NB: ONLY FOR iOS
Oh, it is common in Nigeria. But no problem, I will remove it.

2023-07-11 08:06 UTC, turtledreams requested changes
please move that text out and write that android and ios has different implementations clearly.
keep in mind someone very noob might read these documentation.
Also please add the warning I commented before.
If you have any concerns please let me know so I can help ;)

2023-07-12 09:48 UTC, peterbrown0 commented on react_native_bridged/next.md
> +  Currently you can customize the accent color of your push notifications for both
pushNotification accent color is only for android.

2023-07-12 09:53 UTC, peterbrown0 commented on react_native_bridged/next.md
> +  Here is an example of how data will received in push callbacks:<img src="/guide-media/01GYZ1ETTFDZQAMC8YA0Y0AQ8G" alt="004.png"><br>
Here is an example of how data will **be received in push callbacks. I think the sentence needs "be".

2023-07-19 14:02 UTC, ArtursKadikis approved these changes

2023-07-19 14:02 UTC, merged