[Doc, deeper look] acquire public key cert needs example, problems re…
Countly/countly-sdk-documentation pull request #429
Opened 2023-11-01 09:07 UTC by arifBurakDemiray

…work

2023-11-01 11:49 UTC, arifBurakDemiray commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Doc, deeper look] acquire public key cert needs example, problems rework](https://trello.com/c/LLSaUToG/1042-doc-deeper-look-acquire-public-key-cert-needs-example-problems-rework)

2023-11-06 09:12 UTC, turtledreams requested changes

2023-11-06 09:12 UTC, turtledreams commented on a_deeper_look_at_sdk_concepts/current.md
> +  <span>The produced output would contain information about multiple certificates, they are showing the certificate chain of trust to the respective root certificate authority. The specific cert info
tone should consistent. "they are showing" sounds off. Maybe "it shows"?

2023-11-06 09:12 UTC, turtledreams commented on a_deeper_look_at_sdk_concepts/current.md
> +  To investigate those issues further, sometimes a good way of exploring the cause
looks tautological. I think omitting "To investigate those issues further" would do

2023-11-06 09:12 UTC, turtledreams commented on a_deeper_look_at_sdk_concepts/current.md
> +<p>It's error codes may lead to a solution.</p>
its
it's => it is(has)
its => belongs to 'it'
or you can go for "the error codes here ..."

2023-11-06 13:51 UTC, ArtursKadikis approved these changes

2023-11-06 13:51 UTC, merged