Flutter: Added section to enroll/exit AB with experiment ID
Countly/countly-sdk-documentation pull request #431
Opened 2023-11-03 10:48 UTC by ijunaid

2023-11-03 13:20 UTC, turtledreams approved these changes

2023-11-06 13:49 UTC, ArtursKadikis requested changes
No.

smth like:
# AB experiment testing
## variant level control
### downloading
### accessing
## experiment level control
### downloading
### accessing
### enrolling / exiting

2023-11-07 08:49 UTC, turtledreams approved these changes

2023-11-07 08:50 UTC, turtledreams commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Flutter, doc] Add documentation info for the new testing calls](https://trello.com/c/v2dcrTMr/1058-flutter-doc-add-documentation-info-for-the-new-testing-calls)

2023-11-09 12:07 UTC, merged