[Java, doc] update user profile calls
Countly/countly-sdk-documentation pull request #443
Opened 2023-11-20 12:26 UTC by arifBurakDemiray

2023-11-21 15:26 UTC, ijunaid requested changes

2023-11-21 15:26 UTC, ijunaid commented on java/next.md
> +Countly.instance().userProfile().save();
If calling save() is necessary after configuring user properties, I believe it should be explicitly stated by including a sentence addressing this requirement.
For e.g
Note: Ensure to call Countly.instance().userProfile().save() to send the configured user properties to the server after setting them.

2023-11-22 06:55 UTC, arifBurakDemiray commented on java/next.md
> +Countly.instance().userProfile().save();
Yes, that will be perfect

2023-11-22 07:31 UTC, ijunaid approved these changes

2023-11-22 12:53 UTC, merged