[Java, doc] update location calls
Countly/countly-sdk-documentation pull request #444
Opened 2023-11-20 12:40 UTC by arifBurakDemiray

2023-11-21 15:19 UTC, ijunaid requested changes

2023-11-21 15:19 UTC, ijunaid commented on java/next.md
> +  When location values are set, a separate request will be created to send them
The clarity of this paragraph needs improvement as the wording is somewhat vague, and the sentences are intermingled. As an end user, I require assistance in comprehending the functionality described.

2023-11-21 15:19 UTC, ijunaid commented on java/next.md
> +<p>To disable location tracking:</p>
is by default location is disabled or enabled? is there a way to disable the location during initialization?

2023-11-22 07:08 UTC, arifBurakDemiray commented on java/next.md
> +<p>To disable location tracking:</p>
For the java case if consent is given it is enabled by default and java does not have the ability to disable location during init

2023-11-22 07:21 UTC, ijunaid approved these changes

2023-11-27 05:45 UTC, turtledreams requested changes

2023-11-27 05:45 UTC, turtledreams commented on java/next.md
> +    <span>Latitude and longitude values separated by a comma, e.g. "56.42345,123.45325"</span>
similar to this example please provide examples for other fields too

2023-11-27 05:45 UTC, turtledreams commented on java/next.md
> +  works in a session begin request.
please provide more information about this method and its interaction with the server

2023-11-27 05:45 UTC, turtledreams commented on java/next.md
> +  This information can be used to know your app users better or to send them tailored
"while integrating" sounds off. "this SDK" sounds distant. It would be better to mention cohorts and such and where they will see this info on the server.

2023-12-04 10:00 UTC, turtledreams requested changes

2023-12-05 12:59 UTC, ArtursKadikis requested changes
no "setDisableLocation"

2023-12-05 13:05 UTC, arifBurakDemiray commented
> no "setDisableLocation"

We have documented it if you mean it is missing
https://github.com/Countly/countly-sdk-documentation/blob/28afed9297a66430d09470f202198955b2163c10/java/next.md?plain=1#L526

2023-12-15 08:52 UTC, merged