[Java, doc] add new calls for crash reporting
Countly/countly-sdk-documentation pull request #445
Opened 2023-11-21 09:02 UTC by arifBurakDemiray

2023-11-21 15:10 UTC, ijunaid approved these changes

2023-11-22 12:12 UTC, ArtursKadikis requested changes
this doesn't fully explain the fatal part of a handled exception and the point of the recordUnhandled call

2023-11-29 09:51 UTC, turtledreams requested changes

2023-11-29 09:51 UTC, turtledreams commented on java/next.md
> +// you can also add segments values to inspect it detailed way later on
"inspect it detailed way later on" should go I think

2023-11-29 09:51 UTC, turtledreams commented on java/next.md
> +<p>Following the command adds crash breadcrumb:</p>
following?

2023-11-29 09:51 UTC, turtledreams commented on java/next.md
> +// you can also add segments values to inspect it detailed way later on
oh it was a copy pasta issue from "inspect it in a detailed way later on,"

2023-11-29 09:51 UTC, turtledreams commented on java/next.md
> +  it can be reported with these functions:
rework this sentence

2023-11-30 08:10 UTC, turtledreams approved these changes

2023-11-30 12:51 UTC, merged