[Doc, deeper] Add a section for "What Information Is Collected by the SDK"
Countly/countly-sdk-documentation pull request #472
Opened 2023-12-21 10:32 UTC by arifBurakDemiray

2023-12-21 12:43 UTC, turtledreams requested changes

2023-12-21 12:43 UTC, turtledreams commented on a_deeper_look_at_sdk_concepts/current.md
> +      <th style="width: 78.2857%; text-align: center; vertical-align: middle; height: 22px;" scope="colGroup">Description</th>
![image](https://github.com/Countly/countly-sdk-documentation/assets/62231246/c52ccea8-440c-4696-9c4a-ddf3fb9f5483)
top one is centered

2023-12-21 12:43 UTC, turtledreams commented on a_deeper_look_at_sdk_concepts/current.md
> +<h2 id="h_01HJ5PA5GMQSE8ATC3FJ6VAGP3">Common Metrics</h2>
after "Parameters Sent With Every Request" it would be better to go with "Parameters Specific to Certain Requests" or "Conditional Parameters" as an h2 and under it you can have h3s indicating those special cases

2023-12-21 12:43 UTC, turtledreams commented on a_deeper_look_at_sdk_concepts/current.md
> +      <td style="width: 78.2857%; text-align: center; vertical-align: middle;">Build UUID, iOS SDK</td>
if an item is exclusive to certain SDK mention them as a footnote or in a more prominent manner. Also add an example request or payload below if possible.

2024-01-03 06:29 UTC, turtledreams requested changes

2024-01-03 06:29 UTC, turtledreams commented on a_deeper_look_at_sdk_concepts/current.md
> +  <span>The following description mentions data that is collected by SDK's to perform their functions and implement the required features. Before any of it is sent to the server, it is stored locally
SKDs

2024-01-03 06:29 UTC, turtledreams commented on a_deeper_look_at_sdk_concepts/current.md
> +      <td style="width: 21.7143%; vertical-align: middle; height: 22px; text-align: left;" scope="colGroup">rr</td>
healthcheks dont have rr, so rr is also specific in a way

2024-01-03 06:29 UTC, turtledreams commented on a_deeper_look_at_sdk_concepts/current.md
> +  Addition to session metrics NodeJS SDK sends these metric params. Here is an
this is browser specific not nodejs

2024-01-03 14:23 UTC, ArtursKadikis requested changes
Verticial dividing lines in the tables.

"When sending any network requests to the server, the following things"
things -> information


"Parameters Specific to Certain Requests"
needs a intro. smth like "depending on the request prepared, some additional information might be added"

"Common Metrics"
mention what requests use the common metrics

"if platform can collect"
If they are available for the specific device/sdk/platform

"Also session's start time, end time and duration collected." 
not needed

let us combine the exceptions in a single table
only a single example per topic

2024-01-08 10:10 UTC, ArtursKadikis requested changes
Table justification needs some work

There needs to be some spacing after the table

2024-01-08 10:17 UTC, ArtursKadikis commented
The device ID sources section needs to be iterated uppon

2024-01-08 12:34 UTC, peterBrxwn requested changes
minor changes requested

2024-01-08 12:34 UTC, peterBrxwn commented on a_deeper_look_at_sdk_concepts/current.md
> +        <span> &nbsp; &nbsp; day of the week that request is created at (Countly days start with <br>&nbsp; &nbsp; Sunday as 0)</span>
Instead of (Countly days start with Sunday as 0),
consider 
(For Countly, the week commences on Sunday, designated as index 0)

2024-01-08 12:34 UTC, peterBrxwn commented on a_deeper_look_at_sdk_concepts/current.md
> +        <span> &nbsp; &nbsp; version of the SDK that request is created from</span>
Instead of adding &nbsp; to the beginning to this line, consider adding padding-left to td element achieve this

2024-01-08 12:34 UTC, peterBrxwn commented on a_deeper_look_at_sdk_concepts/current.md
> +        <span> &nbsp; &nbsp; key of the app that request is sent to</span>
Key for the app that is sending the request.

2024-01-08 12:34 UTC, peterBrxwn commented on a_deeper_look_at_sdk_concepts/current.md
> +        <span>&nbsp; &nbsp; </span>package name if collected by the SDK
Package name or store name?

2024-01-08 12:34 UTC, peterBrxwn commented on a_deeper_look_at_sdk_concepts/current.md
> +        <span>&nbsp; &nbsp; </span>User agent (Web SDK)
User agent (Only used by the Web SDK)

2024-01-08 12:34 UTC, peterBrxwn commented on a_deeper_look_at_sdk_concepts/current.md
> +        <span>&nbsp; &nbsp; error happened</span>
error description

2024-01-09 12:38 UTC, turtledreams approved these changes

2024-01-11 12:17 UTC, peterBrxwn approved these changes

2024-01-11 12:17 UTC, peterBrxwn commented on a_deeper_look_at_sdk_concepts/current.md
> +      <td style="width: 25%; vertical-align: middle; text-align: left; padding-left: 10px; height: 10px; border-right: solid 1px;">_binary_images</td>
Other `td` elements have `scope="colGroup"`, shouldn't this one have the same thing?

2024-01-11 12:44 UTC, AliRKat approved these changes
some of the sub headers are not in pascal case, which i just wanted to mention. everything else seems perfectly fine to me.

2024-01-11 12:46 UTC, arifBurakDemiray commented on a_deeper_look_at_sdk_concepts/current.md
> +      <td style="width: 25%; vertical-align: middle; text-align: left; padding-left: 10px; height: 10px; border-right: solid 1px;">_binary_images</td>
dunno added

2024-01-11 18:21 UTC, merged