[Windows, Doc] Backend mode missing doc
Countly/countly-sdk-documentation pull request #474
Opened 2023-12-28 10:53 UTC by arifBurakDemiray

2024-01-03 08:39 UTC, turtledreams requested changes

2024-01-03 09:00 UTC, arifBurakDemiray commented on windows/next.md
> +  deviceId, appKey, name, segment and duration parameters are required. They should
it also mandatory for events

2024-01-09 12:36 UTC, turtledreams approved these changes

2024-01-09 12:36 UTC, turtledreams commented
tldr

2024-01-10 14:52 UTC, ArtursKadikis requested changes
&nbsp; needs to be removed

2024-01-10 15:24 UTC, ArtursKadikis requested changes
expand on the user profile custom modiffier descriptions

2024-01-22 12:57 UTC, merged