[Windows, Doc] Implement metric override
Countly/countly-sdk-documentation pull request #475
Opened 2023-12-29 08:18 UTC by arifBurakDemiray

2024-01-05 08:08 UTC, ijunaid approved these changes
Please update with proper SDK version before merging it on this line:
"This functionality is available since SDK version XX.XX.XX"

2024-01-08 12:43 UTC, peterBrxwn requested changes

2024-01-08 12:43 UTC, peterBrxwn commented on windows/next.md
> +  <p>This functionality is available since SDK version XX.XX.XX.</p>
xx.xx.xx shouldn't we put the actual version number?

2024-01-08 12:43 UTC, peterBrxwn commented on windows/next.md
> +cc.serverUrl = "http://YOUR_SERVER";
For consistency with flutter, serverUrl should be "https://xxx.count.ly"

2024-01-10 15:07 UTC, merged