updated to countlyconsent class
Countly/countly-sdk-documentation pull request #531
Opened 2024-02-07 14:34 UTC by peterBrxwn

2024-02-07 14:36 UTC, peterBrxwn commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Flutter, doc] Rework our doc to use CountlyConsent for referencing consent](https://trello.com/c/uGCL9Xaf/1418-flutter-doc-rework-our-doc-to-use-countlyconsent-for-referencing-consent)

2024-02-11 12:13 UTC, arifBurakDemiray commented on flutter/next.md
> +      <span style="font-weight: 400;">when CountlyConsent.remoteConfig consent is given after it had been removed before (if consents are enabled)</span>
maybe a code tag to the consent

2024-02-11 12:14 UTC, arifBurakDemiray approved these changes
All seems okey

2024-02-12 09:09 UTC, turtledreams requested changes
In User Consent section pls add a sentence or two to tell people that they can use the CountlyConsent inteface to reach all possible consent options and such.
Then ofc you can remove the CountlyConsent prefix in the features list and mention that these are the options you can reach from the interface.

2024-02-19 20:38 UTC, peterBrxwn commented
> In User Consent section pls add a sentence or two to tell people that they can use the CountlyConsent inteface to reach all possible consent options and such.
> Then ofc you can remove the CountlyConsent prefix in the features list and mention that these are the options you can reach from the interface.

Done

2024-02-29 14:00 UTC, peterBrxwn commented on flutter/next.md
> +  You can use CountlyConsent inteface to reach all possible consent options.<br>
done

2024-02-29 14:00 UTC, peterBrxwn commented on flutter/next.md
> +      <span style="font-weight: 400;">when CountlyConsent.remoteConfig consent is given after it had been removed before (if consents are enabled)</span>
done

2024-03-01 12:46 UTC, arifBurakDemiray approved these changes

2024-03-04 07:22 UTC, turtledreams approved these changes

2024-03-04 14:31 UTC, merged