[Android, Doc] update the proguard recommendations
Countly/countly-sdk-documentation pull request #556
Opened 2024-02-21 11:34 UTC by arifBurakDemiray

2024-02-23 06:55 UTC, turtledreams requested changes

2024-02-23 06:55 UTC, turtledreams commented on android/next.md
> +<pre><code class="java">-ignorewarnings
just link or also the rules for hms? thoughts?

2024-02-23 07:04 UTC, arifBurakDemiray commented on android/next.md
> +<pre><code class="java">-ignorewarnings
My first approach was not mentioning at all. But keeping both of them is safe

2024-02-23 10:47 UTC, turtledreams approved these changes

2024-02-27 15:58 UTC, ijunaid approved these changes

2024-02-28 14:40 UTC, merged