[SDKDG] Constructing WebView and Automatic FW
Countly/countly-sdk-documentation pull request #557
Opened 2024-02-21 16:10 UTC by AliRKat

2024-02-23 06:34 UTC, turtledreams requested changes

2024-02-23 06:34 UTC, turtledreams commented on sdk_dev_guide/current.md
>    If the developer has decided on a widget to present, he would call
lets make 'constructing webview url' more agnostic. like you can remove this sentence and some parts of the one below which says display it like this or that. instead those actions should be mentioned at their respective articles and only for the construction you can link to this article.

2024-02-23 11:04 UTC, turtledreams requested changes

2024-02-23 11:04 UTC, turtledreams commented on sdk_dev_guide/current.md
> +  <code>presentFeedbackWidget</code> method by passing a
is it though? how about constructFeedbackWidgetUrl in java?

2024-02-23 11:09 UTC, AliRKat commented on sdk_dev_guide/current.md
> +  <code>presentFeedbackWidget</code> method by passing a
Hmmm, I didn't think that something like that would exist. Assuming is not the best thing to do :D The best way to do it, I guess, would be saying sth like "calling the related method" and when exposed calls in the SDK section are added, adding a link to that section in here.

2024-02-26 09:15 UTC, turtledreams commented on sdk_dev_guide/current.md
> +  would call the related method and pass the chosen widget (<code>CountlyFeedbackWidget</code>)
okay but here we have to know which method that is, don't you think so? 
Think it like this:
auto: fetch with a() => returns b => select b[0] => call c(b[0]) => internally constructs url for b[0] with d(b[0]) => returns url to c => c presents with that url
manual display: fetch with a() => returns b => select b[0] => call d(b[0]) => returns url

so in the future when we get new team members we will give them this document. they should be able to implement the feature in their rust sdk without asking Ali senpai for help. so they should know all functions names, right? like a, c and d. so c will have an internal function d which constructs a url from the given widget. but d will be a standalone method too where developer can use it to get the url. currently I have no info on d's name, as it was not mentioned to me, but from the java implementation it seems like it will be named 'constructFeedbackWidgetUrl '

what do you think?

2024-02-26 09:31 UTC, AliRKat commented on sdk_dev_guide/current.md
> +  would call the related method and pass the chosen widget (<code>CountlyFeedbackWidget</code>)
That is correct, I missed the fact that d's name eventually have to be mentioned within this part even though we are going to add a section for public SDK methods, in here it should be mentioned. thanks for the detailed explanation, I've fixed that change back

2024-02-26 09:34 UTC, turtledreams approved these changes

2024-02-26 14:05 UTC, merged