[RN, Doc] replace deprecated calls
Countly/countly-sdk-documentation pull request #566
Opened 2024-02-26 09:11 UTC by arifBurakDemiray

2024-02-26 09:27 UTC, turtledreams requested changes

2024-02-26 09:27 UTC, turtledreams commented on react_native_bridged/next.md
>    <span>By default, no consent is given. That means that if no consent is enabled, Countly will not work and no network requests related to its features will be sent.</span>
below setconsentenable should be giveConsent

2024-02-26 09:27 UTC, turtledreams commented on react_native_bridged/next.md
>  </p>
you can change the 'before initializing' to during init as it is a config method now.

2024-02-27 07:22 UTC, turtledreams approved these changes

2024-02-27 14:24 UTC, ijunaid approved these changes

2024-02-27 15:02 UTC, merged