[SDKDG] Calls Exposed in the SDK
Countly/countly-sdk-documentation pull request #570
Opened 2024-02-27 10:09 UTC by AliRKat

2024-02-27 12:19 UTC, turtledreams requested changes

2024-02-27 12:19 UTC, turtledreams commented on sdk_dev_guide/current.md
> +  Although method names may vary, the core functionalities remain consistent. Here
lets use a more normative language, like 'should'

2024-02-27 12:19 UTC, turtledreams commented on sdk_dev_guide/current.md
> +  are the primary feedback-related methods:
mention that these methods should be exposed through an interface if applicable. that interface should be named 'feedback' etc

2024-02-27 12:19 UTC, turtledreams commented on sdk_dev_guide/current.md
> +<pre><code>Countly.getAvailableFeedbackWidgets()</code></pre>
examples should have an interface

2024-02-27 12:19 UTC, turtledreams commented on sdk_dev_guide/current.md
> +  Although method names may vary, the core functionalities remain consistent. Here
also mention not all platforms will have all of these but this list is exhaustive

2024-02-27 12:19 UTC, turtledreams commented on sdk_dev_guide/current.md
> +<p>Presents a chosen feedback widget in an alert dialog.</p>
web shows it in iframe. alertdialog has a webview in it which actually shows the widget. so this sentence should be more generalizable without dissecting each option

2024-02-27 12:19 UTC, turtledreams commented on sdk_dev_guide/current.md
> +</p>
there is also a method that returns the url, no?

2024-02-27 12:19 UTC, turtledreams commented on sdk_dev_guide/current.md
> +  Downloads data for a specific widget to be displayed with a custom UI. This data
no need to explain what the returned data will be used for. you will explain that in its respective section

2024-02-27 14:52 UTC, turtledreams approved these changes

2024-02-27 18:01 UTC, ArtursKadikis requested changes
needs to be tweaked as per slack info

2024-03-04 07:18 UTC, turtledreams requested changes

2024-03-04 07:18 UTC, turtledreams commented on sdk_dev_guide/current.md
> +Countly.feedback().reportFeedbackWidgetManually(CountlyFeedbackWidget widgetInfo, JSONObject widgetData, Map&lt;string, object&gt; widgetResult);
mention these return sth or nothing(void)

2024-03-04 14:16 UTC, ArtursKadikis requested changes
needs to be reworked

2024-03-06 13:03 UTC, ArtursKadikis requested changes
consent
no init time config options
where are the callback?
~ "the feedback interface should expost the following functions"

2024-03-11 14:08 UTC, merged