[Flutter, Doc] update code blocks lang to dart
Countly/countly-sdk-documentation pull request #582
Opened 2024-03-04 12:03 UTC by arifBurakDemiray

2024-03-04 13:37 UTC, peterBrxwn commented
![Screenshot 2024-03-04 at 14 33 58](https://github.com/Countly/countly-sdk-documentation/assets/43280227/7d70835c-12aa-4b99-8bb9-4040d2ad19f6)

Some javascript code are still left.

Also, search the codebase for `<code>` and consider adding `class="dart"` to the relevant ones.

2024-03-04 13:37 UTC, peterBrxwn requested changes

2024-03-04 13:37 UTC, peterBrxwn commented on flutter/next.md
> +  <code>removeConsent</code> or <code class="dart">giveConsent</code> methods.
Also add `class="dart"` to the first code tag on this line

2024-03-04 13:48 UTC, arifBurakDemiray commented on flutter/next.md
> +  <code>removeConsent</code> or <code class="dart">giveConsent</code> methods.
I think adding class to those short ones are not needed because there will be no styling at all. So I removed from the second one

2024-03-05 00:40 UTC, peterBrxwn approved these changes

2024-03-08 11:56 UTC, merged