[DevGuide] Crash filtering details
Countly/countly-sdk-documentation pull request #637
Opened 2024-04-16 10:55 UTC by arifBurakDemiray

2024-04-16 11:56 UTC, turtledreams commented
awesome, we might expand it a bit with some

2024-04-17 11:33 UTC, turtledreams commented
Adding the whole team for review because we all will implement this feature in our SDKs. So we better check if everything is clear for us and we can plan or discuss details starting from here.

2024-04-18 08:22 UTC, AliRKat requested changes
Content-wise perfect work 🚀 

Visual-wise, I feel the language is clear and easy to read. My only suggestion is to turn the normally written lists into bulleted lists. Bulleted lists are much easier to review and wouldn't confuse them with other sections.

2024-04-18 08:22 UTC, AliRKat commented on sdk_dev_guide/current.md
> +<p>The crash data object must contain:</p>
I think we should turn these into bulleted list

2024-04-18 08:22 UTC, AliRKat commented on sdk_dev_guide/current.md
> +</p>
Also, this section should be bulleted list in my opinion

2024-04-18 10:06 UTC, peterBrxwn approved these changes

2024-04-19 08:17 UTC, AliRKat approved these changes
perfecto 👌

2024-05-24 12:08 UTC, turtledreams approved these changes

2024-05-24 12:08 UTC, merged