[Cpp] SetMetrics method added
Countly/countly-sdk-documentation pull request #645
Opened 2024-04-25 10:31 UTC by AliRKat

2024-04-25 10:32 UTC, AliRKat commented
![](https://github.trello.services/images/mini-trello-icon.png) [[C++, Doc] Add SetMetrics section](https://trello.com/c/5QVKdL0K/1688-c-doc-add-setmetrics-section)

2024-04-26 05:16 UTC, turtledreams requested changes

2024-04-26 05:16 UTC, turtledreams commented on cpp/next.md
> +<h2 id="h_01HWABRGA5S8N9CJHT286D29M8">Custom Metrics</h2>
seems like it does not follow the document structure we have:
**Other Features and Notes**
...
* Example Integrations
* SDK storage and Requests
  * Setting Event Queue Threshold
...
...
* Custom Metrics

2024-04-26 05:16 UTC, turtledreams commented on cpp/next.md
> +  <a href="https://support.count.ly/hc/en-us/articles/9290669873305-A-Deeper-Look-at-SDK-concepts#h_01HJ5PA5GMQSE8ATC3FJ6VAGP3" target="_blank" rel="noopener noreferrer">here</a>.
looks like this link will be better. now when I checked the other one did not have _device

2024-04-26 05:16 UTC, turtledreams commented on cpp/next.md
> +  Device Metrics information is sent to the server with every 'begin session' request.
lets add we send them when asking for remote config too

2024-04-26 05:16 UTC, turtledreams commented on cpp/next.md
> +ct.SetMetrics("Windows 10", "10.22", "Mac", "800x600", "Carrier", "1.0");
'mac' can be 'Lenovo'

2024-04-26 12:30 UTC, turtledreams approved these changes

2024-04-26 12:30 UTC, merged