[Unity] View Functionality Added
Countly/countly-sdk-documentation pull request #650
Opened 2024-05-29 15:33 UTC by AliRKat

2024-05-29 15:33 UTC, AliRKat commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Unity, Doc] Add new view methods remove deprecated ones](https://trello.com/c/s1HwIBFY/1818-unity-doc-add-new-view-methods-remove-deprecated-ones)

2024-05-30 06:37 UTC, turtledreams requested changes

2024-05-30 06:37 UTC, turtledreams commented on unity/next.md
> -<h1 id="h_01HABTZ315E40XEHJHRMQMW0J6">View Tracking</h1>
these titles could have links pointing at them. These links are would use the id of the title. so tittle ids should not change

2024-05-30 06:48 UTC, arifBurakDemiray commented on unity/next.md
> +  In the SDK, all view-related functionality can be browsed from the returned interface
please also add user guide documentation for it
https://support.count.ly/hc/en-us/articles/4444616740249-Flows

2024-05-30 06:49 UTC, arifBurakDemiray approved these changes

2024-05-31 05:36 UTC, turtledreams requested changes

2024-05-31 05:36 UTC, turtledreams commented on unity/next.md
> +  <a href="http://resources.count.ly/docs/view-analytics" target="_blank" rel="noopener noreferrer">here</a>.
isnt there something more up to date?
also maybe it would be better to move this paragraph to the top of the feature h1

2024-06-03 13:02 UTC, peterBrxwn approved these changes

2024-06-04 11:46 UTC, turtledreams approved these changes

2024-06-04 11:46 UTC, merged