[Android, Doc] add supprted types
Countly/countly-sdk-documentation pull request #655
Opened 2024-06-25 09:40 UTC by arifBurakDemiray

2024-06-25 10:21 UTC, turtledreams requested changes
this will be starting from 24.4.2 so gotta mention that with a warning thingy (4.0 and 4.1 wont have arrays etc)

2024-07-01 09:09 UTC, peterBrxwn approved these changes

2024-07-01 09:59 UTC, peterBrxwn approved these changes
`&lt;` and `&gt;` should be replaced with < and >.

2024-07-03 05:31 UTC, turtledreams requested changes

2024-07-03 05:31 UTC, turtledreams commented on android/next.md
> +    In version <strong>24.7.0</strong>, support for Array, List, and JSONArray
now instead of a minor we decided to release a major so this not necessary anymore as the doc should be for 24.7.X and all 24.7.0+ users should have this

2024-07-03 06:01 UTC, arifBurakDemiray commented on android/next.md
> +    In version <strong>24.7.0</strong>, support for Array, List, and JSONArray
ah ok

2024-07-03 06:56 UTC, turtledreams approved these changes

2024-07-03 06:56 UTC, merged