Create sc-SE-session.md
Countly/countly-sdk-documentation pull request #657
Opened 2024-06-27 13:11 UTC by AliRKat

few parts might need to update, waiting your opinions

2024-06-27 13:12 UTC, AliRKat commented
![](https://github.trello.services/images/mini-trello-icon.png) [[SDK-Doc] Session scenario tests added in GitHub](https://trello.com/c/6UbebWsw/1878-sdk-doc-session-scenario-tests-added-in-github)

2024-06-28 07:16 UTC, arifBurakDemiray commented on test_scenarios/sc-SE-session.md
> +        endSession();
tabbings are seeming like 4 please do it 2 afaik it is the way for doc

2024-06-28 07:16 UTC, arifBurakDemiray approved these changes

2024-06-28 12:52 UTC, AliRKat commented on test_scenarios/sc-SE-session.md
> +        endSession();
thank you, fixed tabbings

2024-07-03 05:39 UTC, turtledreams requested changes
can you check the current flutter tests for these and update it accordingly.  also take the current observations from the notes.md of those flutter tests and add below

2024-08-06 07:09 UTC, turtledreams commented
@AliRKat the more this waits, scarier it will get for you

2024-08-07 12:45 UTC, turtledreams approved these changes

2024-08-07 12:45 UTC, merged