[Android] User Feedback Section Updated
Countly/countly-sdk-documentation pull request #665
Opened 2024-07-04 13:08 UTC by AliRKat

2024-07-04 13:08 UTC, AliRKat commented
![](https://github.trello.services/images/mini-trello-icon.png) [[SDK, Doc] [Current: Web, Unity] Updating Mumbo Jumbo User Feedback Sections](https://trello.com/c/330rma6c/1886-sdk-doc-current-web-unity-updating-mumbo-jumbo-user-feedback-sections)

2024-07-04 14:08 UTC, arifBurakDemiray reviewed
I am not sure here, I will wait for Big D's thoughts

2024-07-08 09:44 UTC, turtledreams requested changes
also the picture thingy we talked about

2024-07-08 09:44 UTC, turtledreams commented on android/next.md
> +<div class="callout callout--info">
lets move this under feedback widget h2

2024-07-08 11:13 UTC, arifBurakDemiray approved these changes

2024-07-10 12:45 UTC, merged