[Flutter] User Feedback Update
Countly/countly-sdk-documentation pull request #666
Opened 2024-07-05 11:48 UTC by AliRKat

2024-07-05 11:49 UTC, AliRKat commented
![](https://github.trello.services/images/mini-trello-icon.png) [[SDK, Doc] [Current: Web, Unity, Android, Flutter] Updating Mumbo Jumbo User Feedback Sections](https://trello.com/c/330rma6c/1886-sdk-doc-current-web-unity-android-flutter-updating-mumbo-jumbo-user-feedback-sections)

2024-07-05 11:51 UTC, arifBurakDemiray approved these changes

2024-07-08 09:46 UTC, turtledreams requested changes

2024-07-10 12:45 UTC, turtledreams approved these changes

2024-07-10 12:45 UTC, merged