[iOS] UserFeedback Update
Countly/countly-sdk-documentation pull request #667
Opened 2024-07-08 09:58 UTC by AliRKat

2024-07-08 09:59 UTC, AliRKat commented
![](https://github.trello.services/images/mini-trello-icon.png) [[SDK, Doc] [Current: Web, Unity, Android, Flutter, iOS] Updating Mumbo Jumbo User Feedback Sections](https://trello.com/c/330rma6c/1886-sdk-doc-current-web-unity-android-flutter-ios-updating-mumbo-jumbo-user-feedback-sections)

2024-07-08 11:14 UTC, arifBurakDemiray approved these changes

2024-07-10 12:46 UTC, turtledreams requested changes

2024-07-10 12:46 UTC, turtledreams commented on ios/next.md
> +<div class="callout callout--info">
this should move

2024-07-10 12:50 UTC, AliRKat commented on ios/next.md
> +<div class="callout callout--info">
updated

2024-07-10 12:53 UTC, turtledreams approved these changes

2024-07-10 12:53 UTC, merged