[Android] update that orientation changes is enabled by default
Countly/countly-sdk-documentation pull request #671
Opened 2024-07-19 07:18 UTC by arifBurakDemiray

2024-07-24 16:17 UTC, turtledreams approved these changes

2024-07-24 16:18 UTC, turtledreams requested changes
lets add to current too and publish

2024-07-25 06:45 UTC, arifBurakDemiray commented
published it

2024-08-01 11:49 UTC, turtledreams approved these changes

2024-08-01 11:49 UTC, merged