device ID interface documentation
Countly/countly-sdk-documentation pull request #676
Opened 2024-08-01 16:06 UTC by peterBrxwn

2024-08-01 17:10 UTC, turtledreams requested changes
lets not advertise merge/nonmerge calls
lets only provide setID
and we have to keep the old call still because 7.0 users will have to use that. find a creative way to display both pls

2024-08-06 07:11 UTC, turtledreams requested changes
hmm did not like this. Lets make like this: discard this commit and in previous commit add a link to the previous doc's device id section in the callout and mention 7.0 should use that method.

2024-08-07 12:50 UTC, turtledreams requested changes
current is 24.7.0. you should not create a new file for 24.7.0. You should link to an older documentation

2024-08-08 05:57 UTC, turtledreams requested changes
1. links in next and current are different
2. now you removed mentioning setID and temp calls are available from 24.7.1 => customer dont know why they should use those links

2024-08-08 06:17 UTC, arifBurakDemiray commented on flutter/current.md
> +    <strong>Click <a href="https://support.countly.com/hc/en-us/articles/34539364044697" target="_blank" rel="noopener noreferrer">here</a>  to access the documentation for version 24.7.0</strong>
just to simplify this link, we can use hc/en-us/articles/34539364044697 to make it more pleasant I think

@turtledreams what do you think? Should we all go for short version

2024-08-08 06:22 UTC, arifBurakDemiray reviewed
🤖

2024-08-08 07:54 UTC, turtledreams commented on flutter/current.md
> +    <strong>Click <a href="https://support.countly.com/hc/en-us/articles/34539364044697" target="_blank" rel="noopener noreferrer">here</a>  to access the documentation for version 24.7.0</strong>
when viewed it is nice, true, but I dont want to micromanage to that level, as already the iteration on bigger things taking time. when a link is added through zendesk's ui it should be shortening it as you mentioned, if possible I prefer that too, but not mandatory

2024-08-08 11:46 UTC, turtledreams approved these changes

2024-08-08 11:46 UTC, merged