[Unity] User Profile Update
Countly/countly-sdk-documentation pull request #677
Opened 2024-08-01 18:13 UTC by AliRKat

2024-08-01 18:13 UTC, AliRKat commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Unity, Doc] User Profile Update](https://trello.com/c/alvxl7hQ/1939-unity-doc-user-profile-update)

2024-08-02 12:06 UTC, arifBurakDemiray commented on unity/next.md
> +  This documentation is for the Countly Unity SDK version 24.8.X. The SDK source
not just user profile update, plus version

2024-08-02 12:07 UTC, arifBurakDemiray approved these changes

2024-08-02 12:17 UTC, arifBurakDemiray commented on unity/next.md
> +<br>// Provide single user property as key and value
dont use br bro, just enter

2024-08-02 12:38 UTC, AliRKat commented on unity/next.md
> +<br>// Provide single user property as key and value
sometimes zendesk adds those when i enter. i am no maniac who manually adds br in there :D

2024-08-02 12:38 UTC, AliRKat commented on unity/next.md
> +  This documentation is for the Countly Unity SDK version 24.8.X. The SDK source
renamed PR

2024-08-02 12:57 UTC, arifBurakDemiray commented on unity/next.md
> +<br>// Provide single user property as key and value
:hulk:

2024-08-02 12:57 UTC, arifBurakDemiray commented on unity/next.md
> +  This documentation is for the Countly Unity SDK version 24.8.X. The SDK source
you are here ❤️

2024-08-06 07:13 UTC, turtledreams requested changes

2024-08-06 07:13 UTC, turtledreams commented on unity/next.md
> +  <p>User Profiles is an enterprise-level plugin.</p>
lets change this ali

2024-08-06 11:25 UTC, peterBrxwn approved these changes

2024-08-08 06:00 UTC, turtledreams approved these changes

2024-08-08 06:00 UTC, merged