[Android] update user profile docs
Countly/countly-sdk-documentation pull request #678
Opened 2024-08-02 12:31 UTC by arifBurakDemiray

2024-08-02 12:46 UTC, AliRKat approved these changes
Cool work. I'd suggest 2 things.
1- at the end of the modifying data section, there's this sentence in line 2163 which says always call save. I would not keep that in
2- there's a small typo for saying duplicate on line 2155

2024-08-06 07:08 UTC, turtledreams requested changes

2024-08-06 07:08 UTC, turtledreams commented on android/next.md
> +  <p>User Profiles is an enterprise-level plugin.</p>
lets change this arif

2024-08-08 06:01 UTC, turtledreams approved these changes

2024-08-08 06:02 UTC, merged