iOS: Updated doc with 24.7.1 changes
Countly/countly-sdk-documentation pull request #680
Opened 2024-08-06 16:41 UTC by ijunaid

2024-08-06 19:39 UTC, arifBurakDemiray requested changes
cuple de changes

2024-08-06 19:39 UTC, arifBurakDemiray commented on ios/current.md
> +    <a href="https://count.ly/enterprise-edition">Enterprise Edition</a> and built-in
please also change enterprie link

2024-08-06 19:39 UTC, arifBurakDemiray commented on ios/current.md
> -    <a href="https://count.ly/enterprise-edition">Enterprise Edition</a> subscription.
countly.com/enterprise

2024-08-06 19:39 UTC, arifBurakDemiray commented on ios/current.md
> +    <a href="https://count.ly/enterprise-edition">Enterprise Edition</a> and built-in
same here

2024-08-07 07:46 UTC, ijunaid commented on ios/current.md
> -    <a href="https://count.ly/enterprise-edition">Enterprise Edition</a> subscription.
nice catch 👍

2024-08-07 07:52 UTC, arifBurakDemiray approved these changes

2024-08-08 06:07 UTC, turtledreams requested changes

2024-08-08 06:07 UTC, turtledreams commented on ios/current.md
> +  <p>For SDK version 24.7.0 you should use the below methods:</p>
lets remove the old methods from this docs and lets add a link to an older doc for those. we can mention the methods here are available from 24.7.1 and prior to that version they should check out the link.

2024-08-20 10:08 UTC, turtledreams approved these changes

2024-08-20 10:08 UTC, merged