work in progress
Countly/countly-sdk-documentation pull request #684
Opened 2024-08-14 13:14 UTC by peterBrxwn

2024-08-15 12:41 UTC, peterBrxwn commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Flutter docs] View documentation](https://trello.com/c/rUBCKgCC/1925-flutter-docs-view-documentation)

2024-08-16 11:34 UTC, arifBurakDemiray requested changes
cuple de f

2024-08-16 11:34 UTC, arifBurakDemiray commented on flutter/current.md
> +<h2 id="h_01HAVQDM5TD5ZGVAC5GCABTXTF">Automatic Views</h2>
so for automatic views, flutter provdes those?
what about enabling it or disablng it

2024-08-20 08:43 UTC, AliRKat requested changes

2024-08-20 08:43 UTC, AliRKat commented on flutter/current.md
> +<h2 id="h_01HAVQDM5TD5ZGVAC5GCABTXTF">Automatic Views</h2>
Agreed with Arif on this one, it should be mentioning how to enable automatic views etc. Android doc has a nice refer to this

2024-08-20 13:58 UTC, turtledreams requested changes
we dont have autoview tracking so you can remove that. instead the intro is fine, but you can add a couple more sentence there.

2024-08-27 13:27 UTC, peterBrxwn commented on flutter/current.md
> +<h2 id="h_01HAVQDM5TD5ZGVAC5GCABTXTF">Automatic Views</h2>
No option to enable or disable on flutter.

2024-08-27 13:30 UTC, arifBurakDemiray commented on flutter/current.md
>  <p>
what about the body, you should also remove the body

2024-08-27 13:30 UTC, arifBurakDemiray commented on flutter/next.md
> -<h2 id="h_01HAVQDM5TD5ZGVAC5GCABTXTF">Automatic Views</h2>
what about the body, you should also remove the body

2024-08-27 13:31 UTC, peterBrxwn commented on flutter/next.md
> -<h2 id="h_01HAVQDM5TD5ZGVAC5GCABTXTF">Automatic Views</h2>
alright

2024-08-27 13:32 UTC, arifBurakDemiray commented on flutter/current.md
> +  For adding segmentation to all automatic views, please refer to the
If we dont have automatic views here, we can rename the "automatic views" here to something else

2024-08-27 13:32 UTC, peterBrxwn commented on flutter/current.md
>  <p>
done

2024-08-27 13:33 UTC, peterBrxwn commented on flutter/current.md
> +  For adding segmentation to all automatic views, please refer to the
Isn't this the body you suggested I remove? because I have removed it.

2024-08-27 13:46 UTC, arifBurakDemiray commented on flutter/current.md
> +  For adding segmentation to all automatic views, please refer to the
Yeap, What was that about

2024-10-04 07:35 UTC, turtledreams approved these changes

2024-10-04 10:45 UTC, AliRKat approved these changes

2024-10-07 08:36 UTC, arifBurakDemiray approved these changes

2024-10-30 14:00 UTC, turtledreams approved these changes

2024-10-30 14:00 UTC, merged