[Flutter] Added documentation for runZonedGuarded
Countly/countly-sdk-documentation pull request #688
Opened 2024-08-15 12:24 UTC by peterBrxwn

2024-08-15 12:31 UTC, peterBrxwn commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Flutter Docs] Added documentation for runZonedGuarded](https://trello.com/c/keDvd90X/1951-flutter-docs-added-documentation-for-runzonedguarded)

2024-08-16 11:31 UTC, arifBurakDemiray approved these changes

2024-08-20 08:38 UTC, AliRKat approved these changes

2024-08-20 12:09 UTC, turtledreams requested changes

2024-08-20 12:09 UTC, turtledreams commented on flutter/current.md
> +<div class="callout callout--warning">
lets do the opposite. reason: lets make it so that removing unnecessary parts in a major is easier. for example just removing the version callout should be enough when we release a major.
By opposite I mean:
1. cut and paste inside the call out
```
<p>
  If you want to catch Dart errors, run your app inside a Zone and supply
  <code>Countly.recordDartError</code> to the <code>onError</code> parameter:
</p>
<pre><code class="dart">void main() {
  runZonedGuarded&lt;Future&lt;void&gt;&gt;(() async {
    runApp(MyApp());
  }, Countly.recordDartError);
}</code></pre>
```
2. change wording to sth like: "if you are using SDK version 24.7.1 or smaller u will need to to blablab to catch dart errors"

2024-08-28 11:11 UTC, peterBrxwn commented on flutter/current.md
> +<div class="callout callout--warning">
done

2024-08-28 11:20 UTC, peterBrxwn commented
<img width="754" alt="Screenshot 2024-08-28 at 12 06 45" src="https://github.com/user-attachments/assets/c27f13aa-a4d6-464c-8d59-8e756a298553">

2024-10-04 07:32 UTC, turtledreams approved these changes

2024-10-04 07:33 UTC, merged