[SdkDevGuide] propose param logging example and constructor logging
Countly/countly-sdk-documentation pull request #691
Opened 2024-08-22 09:20 UTC by arifBurakDemiray

2024-08-22 09:23 UTC, AliRKat approved these changes

2024-08-22 09:23 UTC, AliRKat commented on sdk_dev_guide/current.md
> +  <li>
same here

2024-08-22 09:23 UTC, AliRKat commented on sdk_dev_guide/current.md
> +  <li>
why these did change

2024-08-22 09:25 UTC, arifBurakDemiray commented on sdk_dev_guide/current.md
> +  <li>
probably zendesk formatted them

2024-08-22 09:25 UTC, arifBurakDemiray commented on sdk_dev_guide/current.md
> +  <li>
probably zendesk formatted them

2024-08-22 10:11 UTC, turtledreams requested changes

2024-08-22 10:11 UTC, turtledreams commented on sdk_dev_guide/current.md
> +I: [Info] [Countly] [ModuleEvent] Constructor, something bla bla</code></pre>
definitely no bla bla and dont see too much value for constructor now. can you show me a real example before and after to judge

2024-08-22 11:51 UTC, arifBurakDemiray commented on sdk_dev_guide/current.md
> +I: [Info] [Countly] [ModuleEvent] Constructor, something bla bla</code></pre>
For example in here we dont know where it is logged. If someone who is not familiar with this SDK cannot know the place where this is logged.
It might be logged somewhere else
https://github.com/Countly/countly-sdk-unity/blob/9ed91fad4e9752e6ff7e4333bfc827931f884dee/Assets/Countly/Plugins/CountlySDK/Services/SessionCountlyService.cs#L44

2024-08-22 11:52 UTC, arifBurakDemiray commented on sdk_dev_guide/current.md
> +I: [Info] [Countly] [ModuleEvent] Constructor, something bla bla</code></pre>
This might become to
[SessionCountlyService] Constructor, Automatic session tracking disabled!

2024-08-22 11:52 UTC, arifBurakDemiray commented on sdk_dev_guide/current.md
> +I: [Info] [Countly] [ModuleEvent] Constructor, something bla bla</code></pre>
but yeah you are right maybe it is not to make so much effort

2024-08-23 09:47 UTC, turtledreams approved these changes

2024-08-23 09:47 UTC, merged