[Android] feedback widgets tweak functions
Countly/countly-sdk-documentation pull request #701
Opened 2024-10-10 10:44 UTC by arifBurakDemiray

2024-10-11 13:14 UTC, turtledreams requested changes

2024-10-11 13:14 UTC, turtledreams commented on android/next.md
>  </p>
we want to get rid of the getavailablewidgets and such below, thats why we introduce these methods

2024-10-14 07:21 UTC, arifBurakDemiray commented on android/next.md
>  </p>
yes but are not we are going to keep the old doc for now?

2024-10-22 14:57 UTC, AliRKat requested changes
great work bro, i think with few lines this is ready to go

2024-10-22 14:57 UTC, AliRKat commented on android/next.md
> +  widgets, you can read the <a href="#h_01J9TZ1VZSG732EYVH1X9M2D04">advanced</a>
there was something wrong with this link you might wanna check it again. It doesn't go to the link or section when I click on it. I'd suggest adding the full link there, also maybe labeling "advanced section" as the link can be a better look

2024-10-22 14:57 UTC, AliRKat commented on android/next.md
> +<h3 id="h_01J9V00SX40115R37EBQKDF1HJ">NPS</h3>
Adding a few lines on top of the code blocks can make it look much better, I think. This way, it looks a bit alien to me.

2024-10-22 14:57 UTC, AliRKat commented on android/next.md
> +<pre><code>Countly.sharedInstance().feedback().presentSurvey(Context context)
Same with NPS

2024-10-22 14:57 UTC, AliRKat commented on android/next.md
> +<pre><code>Countly.sharedInstance().feedback().presentRating(Context context)
Same with NPS and Survey :D

2024-10-22 14:57 UTC, AliRKat commented on android/next.md
> +  <a href="https://support.count.ly/hc/en-us/articles/9290669873305-A-deeper-look-at-SDK-concepts#h_01JA7E8H963VYQV6BNR6TB9489" target="_blank" rel="noopener">resource</a>.
link didn't go to the section, is it me or is there a problem

2024-10-24 12:57 UTC, arifBurakDemiray commented on android/next.md
> +  <a href="https://support.count.ly/hc/en-us/articles/9290669873305-A-deeper-look-at-SDK-concepts#h_01JA7E8H963VYQV6BNR6TB9489" target="_blank" rel="noopener">resource</a>.
it is the new deeper look doc, this https://github.com/Countly/countly-sdk-documentation/pull/703

2024-10-24 13:05 UTC, arifBurakDemiray commented on android/next.md
> +  widgets, you can read the <a href="#h_01J9TZ1VZSG732EYVH1X9M2D04">advanced</a>
lets remove from here, we mention it below

2024-10-31 08:07 UTC, turtledreams commented
made it shorter:
![image](https://github.com/user-attachments/assets/fbf65ba3-c899-4300-93d0-be4c27d0543b)

2024-10-31 08:07 UTC, turtledreams approved these changes

2024-10-31 08:31 UTC, AliRKat approved these changes

2024-10-31 11:33 UTC, arifBurakDemiray commented
But is not this become not that much descriptive, I loved the shorter one but it became less descriptive. Anyone should understand the way it is now but they need to think

2024-10-31 11:51 UTC, turtledreams commented
> Member

maybe bold titled in between?

2024-10-31 11:56 UTC, arifBurakDemiray commented
No I guess no need, If we think that they will not read the texts and they just do copy paste the code blocks, this is so enough. In a moment, I thought mb this is not complete, but from the eyes of the developer who will read this, I would do only copy pasta 😅

2024-10-31 12:37 UTC, merged