[NodeJS] Doc Update
Countly/countly-sdk-documentation pull request #702
Opened 2024-10-11 13:12 UTC by AliRKat

2024-10-17 10:52 UTC, AliRKat commented
![](https://github.trello.services/images/mini-trello-icon.png) [[SDK, Doc] NodeJS Doc Update](https://trello.com/c/iB3dM8Wz/1984-sdk-doc-nodejs-doc-update)

2024-10-17 11:06 UTC, arifBurakDemiray requested changes
🚀 or 🪨

2024-10-17 11:06 UTC, arifBurakDemiray commented on nodejs/next.md
> +<h2 id="h_01HABTSEDF4A4P0ZKPFN0MNXYR">Beginning a Session</h2>
Ali-dono could you please also make this rely on the doc structure https://github.com/Countly/countly-sdk-documentation/blob/master/documentation_structure.md#:~:text=Consent-,Sessions,-(Intro)

2024-10-17 11:06 UTC, arifBurakDemiray commented on nodejs/next.md
>  <p>&nbsp;</p>
Ali-bro this nbsp things are good if they do not exist 🔫

2024-10-17 11:06 UTC, arifBurakDemiray commented on nodejs/next.md
> +  Here are the properties you can set up on Countly initialization
waoaw does setup seperate 😱

2024-10-17 11:06 UTC, arifBurakDemiray commented on nodejs/next.md
> +    <strong>storage_path</strong> - Where SDK would store data, including id,
you could maybe extract this new storage things to another PR and do refactor to the doc in this PR
choose your side
🟥💊  or 🟦💊

2024-10-17 11:06 UTC, arifBurakDemiray commented on nodejs/next.md
> +<h2 id="h_01HAXVDTRKE32GSAT0EJ4MF7G1">Make Raw Request</h2>
raw? this is a different wording for other SDKs. We use "direct request" term. However I guess this is for custom SDKs thingies?

2024-10-17 11:06 UTC, arifBurakDemiray commented on nodejs/next.md
> +<h2 id="h_01J9XWNKSARED5HETGGR52XGBK">Providing Custom Storage Methods</h2>
Lets make this another PR
And shine like a bright star
Drive your car
Be happy broth'ar'

2024-10-21 08:44 UTC, AliRKat commented on nodejs/next.md
> +<h2 id="h_01J9XWNKSARED5HETGGR52XGBK">Providing Custom Storage Methods</h2>
I think PR is shorter than 250 lines of change, most of the other changes are typos or obvious wrong things, no need for a second PR for this IMO, what does the others think

2024-10-21 11:11 UTC, arifBurakDemiray approved these changes

2024-10-21 12:50 UTC, turtledreams requested changes

2024-10-21 12:50 UTC, turtledreams commented on nodejs/next.md
> +<p>
information here (and 2 paragraphs below too) is partially correct:
- there is no function parameter check by sdk

SDK will only check:
- object provided
- has key
- value is function

please provide accurate information. passing our initial validity check do not ensure they did all correctly

2024-10-21 12:50 UTC, turtledreams commented on nodejs/next.md
> +    storeSet(key, value, callback) -&nbsp; must save the provided key/value pair
callback is still not accurate

2024-10-21 12:50 UTC, turtledreams commented on nodejs/next.md
> +     * @param {String} key - Key for value to store
visually these comments makes it hard to digest. I would recommend listing the type info above instead of here. and for varies something more precise like null or primitive types

2024-10-21 12:50 UTC, turtledreams commented on nodejs/next.md
> +        Before applying this configuration option, we strongly suggest checking
beyond 'strongly suggesting', they have to read it to see the specs. I would recommend a different tone.

2024-10-22 10:47 UTC, turtledreams approved these changes

2024-10-22 10:47 UTC, merged