[DeeperLook] detailed feedback widgets that is generalized
Countly/countly-sdk-documentation pull request #703
Opened 2024-10-15 07:16 UTC by arifBurakDemiray

2024-10-22 14:47 UTC, AliRKat requested changes
Great work my brother from another mother but I think we should update those code blocks and paragraphs for clarity and better looks

2024-10-22 14:47 UTC, AliRKat commented on a_deeper_look_at_sdk_concepts/current.md
> +      The function requires providing a callback to the getAvailableFeedbackWidgets
Is this the intended look? Looks a bit weird because of the plain text IMO
![image](https://github.com/user-attachments/assets/adc9c564-cf54-48c0-8e98-c454d88081ec)

2024-10-22 14:47 UTC, AliRKat commented on a_deeper_look_at_sdk_concepts/current.md
> +    <p>The objects in the returned list would look like this:</p>
same thing and the same look above

2024-10-22 14:47 UTC, AliRKat commented on a_deeper_look_at_sdk_concepts/current.md
> +  information as a list linked to the current user's device ID. Each SDK provides
well not each sdk

2024-10-22 14:47 UTC, AliRKat commented on a_deeper_look_at_sdk_concepts/current.md
> +  have in order to keep track of the widget you have created. Its usage is totally
Grammarly re-wrote something like this:

"
The returned values are the same as those seen on your Countly server, like the widget ID, widget type, widget name, and the tags you have passed while creating the widget. Tags can contain information you would like to have to keep track of the widget you have created. Its usage is left to the developer.
"

I think we can update it

2024-10-24 12:45 UTC, arifBurakDemiray commented on a_deeper_look_at_sdk_concepts/current.md
> +    <p>The objects in the returned list would look like this:</p>
yeap same thing intended

2024-10-24 12:45 UTC, arifBurakDemiray commented on a_deeper_look_at_sdk_concepts/current.md
> +      The function requires providing a callback to the getAvailableFeedbackWidgets
However, @turtledreams what are your opinions?

2024-10-31 12:02 UTC, AliRKat approved these changes

2024-11-01 09:41 UTC, turtledreams approved these changes

2024-11-01 09:42 UTC, merged