[GettingStarted] setID method for getting started
Countly/countly-sdk-documentation pull request #713
Opened 2024-11-05 14:11 UTC by arifBurakDemiray

2024-11-06 14:39 UTC, turtledreams requested changes

2024-11-06 14:39 UTC, turtledreams commented on getting_started/current.md
> +  <button class="article-unsubscribe" style="padding: 10px 20px;" onclick="window.open('https://support.countly.com/hc/en-us/articles/360037754031-Android#h_01HAVQDM5TPKRQAZGXW73GBM90', '_blank')">An
not sure about linking here. this doc is for novice countly users. maybe we can move these links to our advanced doc and just link to there here. in advanced there was also a device id management section

2024-11-07 10:03 UTC, arifBurakDemiray commented on getting_started/current.md
> +  <button class="article-unsubscribe" style="padding: 10px 20px;" onclick="window.open('https://support.countly.com/hc/en-us/articles/360037754031-Android#h_01HAVQDM5TPKRQAZGXW73GBM90', '_blank')">An
mb we could direclty remove those links then
after adding to the advanced we could put link to it?

2024-11-07 10:05 UTC, arifBurakDemiray commented on getting_started/current.md
> +  <button class="article-unsubscribe" style="padding: 10px 20px;" onclick="window.open('https://support.countly.com/hc/en-us/articles/360037754031-Android#h_01HAVQDM5TPKRQAZGXW73GBM90', '_blank')">An
but those links directly linking to the setId docs for all SDKs.

2024-11-12 08:34 UTC, turtledreams commented on getting_started/current.md
> +  <button class="article-unsubscribe" style="padding: 10px 20px;" onclick="window.open('https://support.countly.com/hc/en-us/articles/360037754031-Android#h_01HAVQDM5TPKRQAZGXW73GBM90', '_blank')">An
how about adding those to each SDK's Other Features section, so we can point there also from Device ID Management instead of linking old doc

2024-11-12 10:24 UTC, arifBurakDemiray commented on getting_started/current.md
> +  <button class="article-unsubscribe" style="padding: 10px 20px;" onclick="window.open('https://support.countly.com/hc/en-us/articles/360037754031-Android#h_01HAVQDM5TPKRQAZGXW73GBM90', '_blank')">An
hmm I see, ok then but this will take time

2024-11-12 15:57 UTC, arifBurakDemiray commented on getting_started/current.md
> +  <button class="article-unsubscribe" style="padding: 10px 20px;" onclick="window.open('https://support.countly.com/hc/en-us/articles/360037754031-Android#h_01HAVQDM5TPKRQAZGXW73GBM90', '_blank')">An
but I am linking to the setID method, which is the newest method and all SDKs must have this. Uh I understand now, you mean to move extended change device id thing to the other features part

2024-12-05 06:25 UTC, turtledreams approved these changes

2024-12-05 06:25 UTC, merged