[SDKDevGuide] rc ab with requests
Countly/countly-sdk-documentation pull request #717
Opened 2024-11-11 14:29 UTC by arifBurakDemiray

2024-11-12 08:32 UTC, turtledreams requested changes

2024-11-12 08:32 UTC, turtledreams commented on sdk_dev_guide/current.md
> +<pre>CountlyConfig<strong>.enableRemoteConfigAutomaticTriggers()<br><br>// Logic<br><br></strong>Enables automatic download of the remote config values (in a variable)<br>This will trigger remote con
you wanted "cached/cleared" instead of "cache cleared"?

2024-11-12 08:32 UTC, turtledreams commented on sdk_dev_guide/current.md
> +<pre>CountlyInstance.<strong>downloadSpecificKeys</strong>(keysToInclude, callback)<br><br><strong>// Valid values</strong><br>All nullable, only non null and not empty values are accepted<br>Non val
it seems like we have to mention the types too, like string array and such

2024-11-12 08:32 UTC, turtledreams commented
good work

2024-11-12 15:26 UTC, arifBurakDemiray commented on sdk_dev_guide/current.md
> +<pre>CountlyConfig<strong>.enableRemoteConfigAutomaticTriggers()<br><br>// Logic<br><br></strong>Enables automatic download of the remote config values (in a variable)<br>This will trigger remote con
Hmm it would be more correct yes

2024-11-12 15:27 UTC, arifBurakDemiray commented on sdk_dev_guide/current.md
> +<pre>CountlyInstance.<strong>downloadSpecificKeys</strong>(keysToInclude, callback)<br><br><strong>// Valid values</strong><br>All nullable, only non null and not empty values are accepted<br>Non val
oh I see

2024-12-05 06:20 UTC, turtledreams approved these changes

2024-12-05 06:20 UTC, merged