[SDK-545] Added rating widget
Countly/countly-sdk-documentation pull request #73
Opened 2021-11-16 15:31 UTC by turtledreams

- Added 'Rating widget' section inside the 'Helpers'
- Modified other function calls where their names has changed
- Did not add a 'User Feedback' section yet as it belongs to another ticket

2021-11-17 10:52 UTC, ArtursKadikis requested changes
Needs a slight reordering

2021-11-17 16:27 UTC, ArtursKadikis commented
@itsiprikshit could you please let me know what you think of this doc?

2021-11-18 17:42 UTC, itsiprikshit commented on web/next.md
> +  second one is used to select the element by it's class selector. Also if you
could you please remove `Also` from this last sentence.
`If you want to inject the feedback widget in a specific element, you can do so by specifying the element ID or the class name.` - this would be more suitable.

2021-11-18 17:53 UTC, turtledreams commented on web/next.md
> +  second one is used to select the element by it's class selector. Also if you
Done :)

2021-11-18 22:05 UTC, merged